---

install:
  - choco install strawberryperl
  - SET PATH=C:\Perl5\bin;C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - perl -v
  - if not exist C:\Perl5 mkdir C:\Perl5
  - SET PERL5LIB=C:/Perl5/lib/perl5
  - SET PERL_LOCAL_LIB_ROOT=C:/Perl5
  - SET PERL_MB_OPT=--install_base C:/Perl5
  - SET PERL_MM_OPT=INSTALL_BASE=C:/Perl5
  - cpanm -n Dist::Zilla
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps --missing | cpanm -n
  - cpanm -n Alien::MSYS Alien::libtool24

build: off

test_script:
  - dzil test -v

#  - cpanm -v Text::Hunspell::FFI
# waiting for https://github.com/cosimo/perl5-text-hunspell/pull/11
# before we use the CPAN version
#  - cpanm -v https://github.com/cosimo/perl5-text-hunspell/archive/master.zip

cache:
  - C:\Perl5

shallow_clone: true
